[project]
name = "growme-organic-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "pandas>=2.3.2",
    "playwright",
    "uvicorn>=0.35.0",
]
